# Generated by Django 3.2.5 on 2021-07-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='catalog_pages',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='access',
            name='crm_pages',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='access',
            name='rshipment_pages',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='access',
            name='supplyf_pages',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
