# Generated by Django 3.2.5 on 2021-10-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapi', '0002_auto_20210726_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_marketplace',
            field=models.BooleanField(default=False),
        ),
    ]
